# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-27 20:55
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Page Title')),
                ('slug', models.SlugField(unique=True)),
                ('header', models.BooleanField(default=True, help_text='Generic header with a background', verbose_name='Header with background image')),
                ('header_bg', models.FilePathField(blank=True, null=True, path='/Users/suche010/Documents/Projects/dexalytics.com/assets/images/marketing', verbose_name='Header Background Image')),
                ('subheader', models.CharField(blank=True, help_text='Subheader before content', max_length=200, verbose_name='Header Tagline')),
                ('title_block', models.BooleanField(default=False, help_text='Header block without background', verbose_name='Turn title block on?')),
                ('seo_keywords', models.CharField(blank=True, max_length=50, null=True, verbose_name='Meta Keywords')),
                ('seo_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta Description')),
                ('columns', models.CharField(choices=[('FULL', 'Full Width'), ('HALF', 'Two Columns')], default='FULL', max_length=4)),
                ('sidebar', models.BooleanField(default=False, verbose_name='Turn sidebar on?')),
                ('column_1', ckeditor.fields.RichTextField(help_text='This is left content box')),
                ('column_2', ckeditor.fields.RichTextField(blank=True, help_text="You don't have to fill this in if you have only one column")),
                ('sidebar_text', ckeditor.fields.RichTextField(blank=True, help_text='Sidebar Text if <b>Sidebar</b> is turned on')),
                ('cta', models.BooleanField(default=True, verbose_name='Call to Action Button?')),
                ('cta_text', models.CharField(blank=True, default='Contact Us', help_text='Default is: Contact Us', max_length=30, null=True, verbose_name='Button Text')),
                ('cta_url', models.CharField(blank=True, default='/contact/', help_text='Within our site: /contact/. External Site: https://google.com/', max_length=300, null=True, verbose_name='Button URL')),
                ('footer', models.BooleanField(default=True, verbose_name='Show Footer?')),
                ('socials', models.BooleanField(default=True, verbose_name='Social Icons?')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Update')),
                ('page_status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', help_text='Make sure you set the page status to Publish, otherwise it is hidden.', max_length=1)),
            ],
        ),
    ]
