# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-01 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='header_bg',
            field=models.FilePathField(blank=True, null=True, path='/Users/saun0063/Workspace/dexalytics.com/assets/images/marketing', verbose_name='Header Background Image'),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 17, 45, 35, 525787, tzinfo=utc), verbose_name='Last Update'),
        ),
    ]
