# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-02 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20171102_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketing',
            old_name='page_status',
            new_name='published',
        ),
    ]
