# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-06 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_auto_20171106_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='subheader',
            field=models.CharField(blank=True, help_text='This is the article title and should be a bit longer than the page title.', max_length=200, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='title',
            field=models.CharField(help_text='Try not to exceed more than 50 characters, long URL or page title is not exactly appealing and it also pushes out of the header block.', max_length=200, verbose_name='Page Title'),
        ),
    ]
