# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-02 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20171101_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='header_bg',
            field=models.FilePathField(blank=True, null=True, path='/Users/suche010/Documents/Projects/dexalytics.com/static/images/marketing', verbose_name='Header Background Image'),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update'),
        ),
    ]
