# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-02 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20171102_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='page_status',
            field=models.BooleanField(default=False, help_text='Make sure you set the page status to Publish, otherwise it is hidden.', verbose_name='Publish Page?'),
        ),
    ]
