# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-09 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_auto_20171106_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='header_bg',
            field=models.FilePathField(blank=True, null=True, path='/Users/saun0063/Workshop/dexalytics.com/static/images/marketing', verbose_name='Header Background Image'),
        ),
    ]
