# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 13:31
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('caption', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
                ('screenshot', models.ImageField(upload_to='preview')),
                ('sortable_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Slide',
                'ordering': ('sortable_order',),
            },
        ),
    ]
