# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 13:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideWaypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoint_set', to='preview.Slide')),
            ],
            options={
                'verbose_name': 'Slide Waypoint',
            },
        ),
    ]
